
export interface Product {
   _id: string; // Automatically generated by Sanity
   name: string;
   price: number;
   description: string;
   images: {
     asset:  {
       _ref: string;
       _type: string;
     };
   }[];
   reviews: Review[]; // Array of references to the `Review` type
   ratings: number[]; // Array of numbers
   stockQuantity: number;
   category: "t-shirt" | "short" | "jeans" | "hoodie" | "shirt"; // Specific values from the options
   discountPercent?: number; // Optional
   new?: boolean; // Optional
   selectedSize?: string;
   selectedColor?: string;
   sizes: string[]; // Ensure these are included
   colors: string[]; // Ensure these are included
   quantity:number;
   slug: {
     current: string; // Slug linked to the product name
   };
   tags?: string[]; // Optional array of tags
   onAddToCart?: () => void;
 }
 
 interface Review {
   _id: string; // Reference ID for the review
   user: {
     _ref: string; // Reference to the user who wrote the review
     _type: string;
   };
   comment: string;
   rating: number;
   createdAt: string; // ISO date string

 }
 
//  export type Product = {
//   id: number;
//   image: string;
//   title: string;
//   rating: number;
//   reviews: number;
//   price: number;
//   originalPrice?: number;
//   discount?: number;
//   category?: string;
//   isNew?: boolean;
//   quantity?: number;
// };
